# Generated by Django 6.0.3 on 2026-05-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('estatus', models.BooleanField()),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
    ]
