# Generated by Django 6.0.3 on 2026-04-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.BooleanField()),
            ],
            options={
                'db_table': 'transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadTransporte',
            fields=[
                ('id_unidad', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(blank=True, max_length=30)),
                ('no_economico', models.IntegerField()),
            ],
            options={
                'db_table': 'unidad_transporte',
                'managed': False,
            },
        ),
    ]
