# Generated by Django 6.0.3 on 2026-04-24 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_rol',
            field=models.ForeignKey(db_column='id_rol', null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol'),
        ),
        migrations.AlterField(
            model_name='users',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
