# Generated by Django 6.0.3 on 2026-04-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_users_id_rol_alter_users_id_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Usuarios',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
