# Generated by Django 6.0.3 on 2026-05-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
